# Generated by Django 5.1.3 on 2025-03-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizadores',
            options={},
        ),
        migrations.AlterModelManagers(
            name='utilizadores',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilizadores',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='nome_cliente',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='password',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='username',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
