# Generated by Django 5.1.3 on 2025-03-24 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0002_alter_utilizadores_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizadores',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
