# Generated by Django 5.1.3 on 2025-03-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0003_utilizadores_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=100)),
                ('tipo_aposta', models.CharField(max_length=100)),
                ('odds', models.FloatField()),
                ('valor_apostado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('possiveis_ganhos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aposta', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_aposta'],
            },
        ),
    ]
