# Generated by Django 5.1.3 on 2025-03-25 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0004_aposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApostaMultipla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_apostado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odd_total', models.FloatField()),
                ('possiveis_ganhos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aposta', models.DateTimeField(auto_now_add=True)),
                ('apostas', models.ManyToManyField(related_name='multipla', to='Projeto_Apostas_App.aposta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas_multipla', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
