# Generated by Django 5.1.3 on 2025-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0005_apostamultipla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aposta',
            options={},
        ),
        migrations.RenameField(
            model_name='apostamultipla',
            old_name='odd_total',
            new_name='total_odds',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='status',
        ),
        migrations.AlterField(
            model_name='apostamultipla',
            name='apostas',
            field=models.ManyToManyField(to='Projeto_Apostas_App.aposta'),
        ),
    ]
