# Generated by Django 5.1.3 on 2025-03-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0006_alter_aposta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostamultipla',
            name='possiveis_ganhos',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apostamultipla',
            name='total_odds',
            field=models.FloatField(null=True),
        ),
    ]
