# Generated by Django 5.1.3 on 2025-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0007_alter_apostamultipla_possiveis_ganhos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='away_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='data_jogo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='home_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='jogo_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
