# Generated by Django 5.1.3 on 2025-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0008_aposta_away_team_aposta_data_jogo_aposta_home_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='data_jogo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
