# Generated by Django 5.1.3 on 2025-04-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0009_alter_aposta_data_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='jogo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
