# Generated by Django 5.1.3 on 2025-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0010_alter_aposta_jogo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ganha', 'Ganha'), ('perdida', 'Perdida')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='apostamultipla',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ganha', 'Ganha'), ('perdida', 'Perdida')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='apostamultipla',
            name='total_odds',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
