# Generated by Django 5.1.3 on 2025-04-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_Apostas_App', '0011_aposta_status_apostamultipla_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ganha', 'Ganha'), ('perdida', 'Perdida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
